### ISSUE TITLE
Project is not open source without a license file

### ISSUE THREAD

**Issue by karan** [tdantas/async-if-else#2]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by tdantas** [comment]
you are right @karan 
let me update the readme ! thank you for the heads up

**Comment by tdantas** [comment]
@karan actually if you go to [project manifest](https://github.com/tdantas/async-if-else/blob/master/package.json#L10) you will find the license there.

but I will update the README with the the License

**Comment by tdantas** [comment]
:+1: done https://github.com/tdantas/async-if-else/blob/master/LICENSE
