### ISSUE TITLE
Can you if without an else?

### ISSUE THREAD

**Issue by alanshaw** [tdantas/async-if-else#3]
Can I add an `async.if(x, y)` without an else block? If so would be good for this to be documented!

**Comment by alanshaw** [comment]
...and if not, can has?

**Comment by tdantas** [comment]
@alanshaw you can \0/ 
I will document that [feature](https://github.com/tdantas/async-if-else/blob/master/test.js#L176-L188) 

thank you

**Comment by tdantas** [comment]
> ...and if not, can has?

[would be awesome](https://github.com/tdantas/async-if-else/issues/4) @alanshaw 
will try at night or in the meanwhile if you PR, will be always welcome :)

**Comment by tdantas** [comment]
@alanshaw published [ifNot](https://github.com/tdantas/async-if-else/blob/master/index.js#L7) and the [unless](https://github.com/tdantas/async-if-else/blob/master/index.js#L7) alias.

**Comment by alanshaw** [comment]
:sparkles: awesome! This is such a good idea!

**Comment by tdantas** [comment]
:+1: :beers:
