### ISSUE TITLE
simpler conditional function

### ISSUE THREAD

**Issue by xo-chris** [tdantas/async-if-else#8]
Hi tdantas

I am finding this useful :-).  One thing is I don't seem to be able to do a simple conditional expression in the 'if' part.  So I want to do something like

var doThis = true;
..waterfall syntax...
  async.if(doThis,doThat);

it seems to do this I have to write a new 'doThis' function and callback true?

Can I do this, or this is a feature request?

Cheers

Chris

**Comment by tdantas** [comment]
hey @xo-chris,

now, we are only accepting a `function` as you described. but I could accept a boolean as you suggested.

could you provide me the use case that are you trying to do ?

cheers

**Comment by tdantas** [comment]
@xo-chris 
check this out. I just created a brand [new branch](https://github.com/tdantas/async-if-else/tree/boolean-value-predicate) and added the `possible` feature that you talk about.

check the [test.js](https://github.com/tdantas/async-if-else/blob/boolean-value-predicate/test.js#L322-L335) file and let me know whether is what you have in mind or not.

cheers

**Comment by tdantas** [comment]
@xo-chris I'm closing the issue, but the new brach will be there.

cheers
